version: '3.12'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "online_store"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "localhost"

  web:
    build: ./server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
