version: '3.12'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: DATABASE_USERNAME
      POSTGRES_PASSWORD: DATABASE_PASSWORD
      POSTGRES_DB: DATABASE_NAME

  web:
    build: ./server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /Users/dan4eg/Git_projects/Online-store sneakers/server:/server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
