# Generated by Django 5.0.1 on 2024-02-07 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('size', models.DecimalField(choices=[(35.0, '35.0'), (35.5, '35.5'), (36.0, '36.0'), (36.5, '36.5'), (37.0, '37.0'), (37.5, '37.5'), (38.0, '38.0'), (38.5, '38.5'), (39.0, '39.0'), (39.5, '39.5'), (40.0, '40.0'), (40.5, '40.5'), (41.0, '41.0'), (41.5, '41.5'), (42.0, '42.0'), (42.5, '42.5'), (43.0, '43.0'), (43.5, '43.5'), (44.0, '44.0'), (44.5, '44.5'), (45.0, '45.0')], decimal_places=1, default=35.0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.sneaker')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_quantity', models.IntegerField()),
                ('sneaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shoes.sneaker')),
            ],
        ),
    ]
